### ISSUE TITLE
redirect without trailing slash not working for same URL with slash, second redirect disappearing

### ISSUE THREAD

**Issue by raglannyc** [aaron13100/404solution#17]
Two-part issue here.

I have a redirect for `/demo-page` which does not work when someone goes to `/demo-page/` with the `/` at the end. Is that intended behavior? Doesn't make sense to me.

I have twice created a second redirect for `/demo-page/` and twice it has disappeared from my list of redirects and the redirect stopped working. I do not know what is making it disappear. I created it for a third time just now, tested it, it worked, and it's still in the list of redirects.

**Comment by aaron13100** [comment]
Hey Chris. I just got your message, but I'm traveling today and I'm not
sure when I'll be able to look at this. I wanted to let you know that I
should be able to get back to you in a few days. In the meantime if there
are any messages in the debug log related to what's happening that would be
helpful.
Cheers
-Aaron

On 6 May 2017 04:01, "Chris Laursen" <notifications@github.com> wrote:

Two-part issue here.

I have a redirect for /demo-page which does not work when someone goes to
/demo-page/ with the / at the end. Is that intended behavior? Doesn't make
sense to me.

I have twice created a second redirect for /demo-page/ and twice it has
disappeared from my list of redirects and the redirect stopped working. I
do not know what is making it disappear. I created it for a third time just
now, tested it, it worked, and it's still in the list of redirects.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/aaron13100/404solution/issues/17>, or mute the thread

**Comment by aaron13100** [comment]
Chris, how did you manage to get your pages to work without the trailing slash? For me the trailing slash is always added automatically, even when the "404 Solution" plugin is disabled. Without being able to reproduce that I won't be able to help.
thanks
-Aaron

**Comment by raglannyc** [comment]
I manually added the redirect without the trailing `/`. I didn't realize at the time that WordPress automatically adds the trailing `/` to every URL.

**Comment by aaron13100** [comment]
Cool. Problem solved then. Let me know if there's anything else. :)
